matrix:
  include:
    - language: python
      python: 2.7
      os: linux
    - language: python
      python: 3.6
      os: linux
install:
  - pip install -U pip setuptools
script: |
  set -e
  python setup.py test
