language: python
python:
- '3.6'
- '3.7'
- '2.7'
install:
- pip install -U pip setuptools
- pip install pipenv
- pipenv install --dev
- pipenv run python setup.py develop
script: |
  set -e
  pipenv run pytest
  if python --version 2>&1 | egrep 'Python 3.6' ; then
    pipenv run pytest --doctest-modules lambda_decorators.py
  fi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
    repo: dschep/lambda-decorators
  user: dschep
  password:
    secure: ZdTDuW9nnhLVk0vSzlpHTe0JdUh6YdVUWziJdgqVP/i9RvhtfWoAHh52eUSFei0QM6e/8HjTDnCZuBtL7JmA7Qaz8GPSBRoi0tS0bebCI12nL6hV3ErmPC34WYhERtn2xmaiGBRfpc6HSayOF5OaXCmB36OigtETHldDXZ/xJTph3cGoz5f0tIJvMwAZ8BLAI6oy/UA4kJCr8ZxjTyaUgBVNF8vHfX2TFxPYtnQnb7/KOnFSb5ZPE0VIahhVLkdkIaMNL+GvhFOq7LB1A4PKz6ZsvJUYdPaWDOyQ1ndm38wESaKAQwhebZJm8pVZy55Ska8+NxXq3kBzmPd45KgD20Z9jxTnPlFmeVLZH4qYQwpOQkF9tVRLKXgTQPxb85j2bheYhrHcQYFYDOGliI4w0iOz3ysyepmTcJC6VbYoiOXyp9XimgGIipSTou3DtkcyIUzJhSF7abn6jLYctlofU3WY1GaNbrRy0SgrRuUG7+g3qr1iicA59onvSYb6ezQhri9H5/xRYM0vBX2tv3gVxARtpS3aheg4IlF6o00CM2NxvMIc64rRVWsKFagNpOCdZiJdxRT7tgNw3ddd9PMNI4QUaLTm6Pp4ih6uEhbkDX+8dapBle0SLKaykYXTc9OJzYha3nI9lhR50usm+UvdkzMXTVnQklMza2u1svF0SuQ=
